# Generated by Django 6.0.5 on 2026-07-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0002_rename_like_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['photos', 'posts']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
