# Generated by Django 6.0.5 on 2026-08-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_alter_likes_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
    ]
