# Generated by Django 6.0.5 on 2026-07-05 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendsrequest',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='friendsrequest',
            index=models.Index(fields=['from_user', 'to_user'], name='friends_fri_from_us_fc91fc_idx'),
        ),
        migrations.AddIndex(
            model_name='friendsrequest',
            index=models.Index(fields=['from_user', 'status'], name='friends_fri_from_us_22a969_idx'),
        ),
        migrations.AddIndex(
            model_name='friendsrequest',
            index=models.Index(fields=['to_user', 'status'], name='friends_fri_to_user_e077da_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendsrequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_from_to_user'),
        ),
    ]
