# Generated by Django 6.0.5 on 2026-08-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendsrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendsrequest',
            options={'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friends Requests'},
        ),
    ]
