# Generated by Django 6.0.5 on 2026-07-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_birth_state_profiles_current_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profiles',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='background_pics'),
        ),
    ]
